# Generated by Django 4.2.5 on 2023-10-09 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cookingrecipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cookingrecipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.CookingRecipeIngredients", to="recipes.ingredients"
            ),
        ),
        migrations.AddField(
            model_name="cookingrecipe",
            name="tags",
            field=models.ManyToManyField(related_name="recipes", to="recipes.tag"),
        ),
    ]
