# Generated by Django 4.2.5 on 2023-10-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookingrecipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.CookingRecipeIngredient", to="recipes.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="cookingrecipe",
            name="tags",
            field=models.ManyToManyField(to="recipes.tag"),
        ),
        migrations.AlterField(
            model_name="cookingrecipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_used",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="cookingrecipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_used",
                to="recipes.cookingrecipe",
            ),
        ),
        migrations.DeleteModel(name="CookingRecipeTag",),
    ]
