# Generated by Django 4.2.5 on 2023-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_shoppinglist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookingrecipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="Ингредиенты",
                through="recipes.CookingRecipeIngredient",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="cookingrecipe",
            name="tags",
            field=models.ManyToManyField(related_name="Tег", to="recipes.tag"),
        ),
    ]
