# Generated by Django 3.2.3 on 2023-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_cookingrecipeingredient_unique_ingredient_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cookingrecipeingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'amount'), name='unique_ingredient_amount'),
        ),
    ]
