# Generated by Django 3.2.3 on 2023-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_cookingrecipeingredient_unique_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cookingrecipeingredient',
            name='unique_ingredient_amount',
        ),
        migrations.AddConstraint(
            model_name='cookingrecipeingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient_recipe'),
        ),
    ]
